# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines')
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    containerRegistry: camino.azurecr.io
    prefix: $(containerRegistry)/
    imageName: '$(prefix)che-plugin-registry:$(build.buildId)'

  steps:
  - task: AzureCLI@1
    inputs:
      connectedServiceNameARM: 'camino'
      scriptLocation: inlineScript
      inlineScript: |
        az acr login -n camino
        az aks get-credentials --resource-group camino  --name camino-wus-2
      scriptPath: ''

  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

  - script: docker push $(imageName)
    displayName: 'docker push'

  - script: helm upgrade --install --set=chePluginRegistryImage=$(imageName),global.ingressDomain=c.pizzafactory.jp,global.ingress.class=traefik --namespace=camino che-plugin-registry ./kubernetes/che-plugin-registry/
    displayName: 'upgrade by Helm'
