# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  containerRegistry: camino.azurecr.io
  prefix: $(containerRegistry)/
  imageName: '$(prefix)che-plugin-registry:$(build.buildId)'

steps:
- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'camino: BizSpark (1fbdb4bb-441e-4922-ba1f-ffd04f533ea1)'
    scriptLocation: 'inlineScript'
    inlineScript: az acr login -n $(containerRegistry)

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker push $(imageName)
  displayName: 'docker push'