# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  containerRegistry: camino.azurecr.io
  prefix: $(containerRegistry)/
  imageName: '$(prefix)che-plugin-registry:$(build.buildId)'

jobs:
- job: Build
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines')

  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

- job: Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines')
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: Docker@1
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: camino.azurecr.io

  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

  - script: docker push $(imageName)
    displayName: 'docker push'
